builder: 'ConceptualCaptionsDatasetBuilder'
config:
  url: 'https://storage.cloud.google.com/gcc-data/Train/GCC-training.tsv?_ga=2.191230122.-1896153081.1529438250'
  output_dir: '/Users/jihoon/Downloads'
