run:
  task: 'MultiDatasetEvaluateTaskWithPretrainedModel'
  seed: 2024
  output_dir: &output_dir '/mnt/elice/multimodal/_result/clip-vit-large-patch14'

model:
  model_cls: 'CLIPModel'
  config:
    pretrained_model_name_or_path: 'openai/clip-vit-large-patch14'

processor:
  processor_cls: "CLIPProcessor"
  config:
    pretrained_model_name_or_path: 'openai/clip-vit-large-patch14'

dataset:
  - Flickr30kDatasetBuilder:
      split: 'test'
  - COCOCaptionsDatasetBuilder:
      split: 'test'
  - ARODatasetBuilder:
      split: 'train'
  - CREPEDatasetBuilder:
      split: 'train'
  - SUGARCREPEDatasetBuilder:
      split: 'train'
  - SVODatasetBuilder:
      split: 'train'
  - WinogroundDatasetBuilder:
      split: 'test'

evaluator:
  - RetrievalEvaluator:
      collator:
        collator_cls: 'ImageCollator'
        config:
          max_length: &max_length 64
      k_values:
        - 1
        - 5
        - 10
      output_dir: *output_dir
  - RetrievalEvaluator:
      collator:
        collator_cls: 'ImageURLCollatorForEvaluation'
        config:
          max_length: *max_length
      k_values:
        - 1
        - 5
        - 10
      output_dir: *output_dir
  - AROEvaluator:
      collator:
        collator_cls: 'ImageCollator'
        config:
          max_length: *max_length
      output_dir: *output_dir
  - CrepeEvaluator:
      collator:
        collator_cls: 'ImageCollator'
        config:
          max_length: *max_length
      output_dir: *output_dir
  - SugarCrepeEvaluator:
      collator:
        collator_cls: 'ImageCollator'
        config:
          max_length: *max_length
      output_dir: *output_dir
  - SVOEvaluator:
      collator:
        collator_cls: 'ImageCollator'
        config:
          max_length: *max_length
      output_dir: *output_dir
  - WinogroundEvaluator:
      collator:
        collator_cls: 'ImageCollator'
        config:
          max_length: *max_length
      output_dir: *output_dir
