export HF_DATASETS_CACHE="YOUR_HUGGINGFACE_CACHE_DIR"
export HF_HOME="YOUR_HUGGINGFACE_CACHE_DIR"
export TRAINING_VERBOSITY="detail"

export NCCL_IB_DISABLE="1"
export NCCL_P2P_DISABLE="1"

DEVICES=3
CUDA_VISIBLE_DEVICES=$DEVICES python mining.py \
    --cfg-path 'YOUR_CONFIG_PATH' \
    --root_dir YOUR_EXPORT_ROOT_DIR\
    --export_fname YOUR_EXPORT_FILE_NAME
