r: 16
auto_mapping: null
base_model_name_or_path: 'facebook/dinov2-large'
bias: 'none'
fan_in_fan_out: False
init_lora_weights: True
inference_mode: False
layers_pattern: null
layers_to_transform: null
lora_alpha: 32
lora_dropout: 0.1
revision: null
target_modules: 'all-linear'