run:
  task: 'PretrainedModelEvaluateTask'
  runner: 'RetrievalEvaluator'
  seed: 2024
  max_seq_length: 64

model:
  model_cls: 'CLIPModel'
  config:
    pretrained_model_name_or_path: '/mnt/working/_output/negclip_dinov2_distillbert/checkpoint-200'

processor:
  processor_cls: "CLIPProcessor"
  config:
    pretrained_model_name_or_path: 'openai/clip-vit-base-patch32'

dataset:
  'Flickr30kDatasetBuilder':
    split: 'test'

evaluator:
  k_values:
    - 1
    - 5
    - 10
  output_dir: '/mnt/working/_result/negclip_dinov2_distillbert/checkpoint-125'
