run:
  task: 'TrainTask'
  runner: 'BaseTrainer'
  seed: 2024
  max_seq_length: 64

  device: "cuda"
  world_size: 1
  distributed: False

model:
  model_cls: 'FuseMixModel'
  config_cls: 'FuseMixConfig'
  config:
    text_pretrained_model_name_or_path: 'BAAI/bge-large-en-v1.5'
    vision_pretrained_model_name_or_path: 'facebook/dinov2-giant'
    torch_dtype: 'fp16'
    pool_type: 'cls'

processor:
  processor_cls: "FuseMixProcessor"
  config:
      text_pretrained_model_name_or_path: 'BAAI/bge-large-en-v1.5'
      vision_pretrained_model_name_or_path: 'facebook/dinov2-giant'

dataset:
  'ConceptualCaptionsDatasetBuilder':
    split: 'train'

trainer:
  output_dir: '/mnt/working/multimodal/_output'
  learning_rate: &learning_rate 1.0e-3
  lr_scheduler_type: 'cosine'
  warmup_steps: &warmup_steps 100
  weight_decay: &weight_decay 1.0e-1
  max_steps : &max_steps 250
  save_steps: 25
  logging_steps : 1
  evaluation_strategy: 'no' # 'steps', 'epochs', 'no'

  num_train_epochs: 1
  per_device_train_batch_size : &per_device_batch_size 1024
  gradient_accumulation_steps: &gradient_accumulation 4
  # For memory efficiency.
  gradient_checkpointing : False

  fp16: &fp16 True # use torch.float16
  fp16_opt_level : '01'
  bf16: &bf16 False # Use torch.bfloat16

  group_by_length : False # Whether to order the sample by token length.
  use_cpu : False
  remove_unused_columns : False